"date_format" : "%Y-%m-%d"

"theme-bootstrap-2" :
  "use" : "theme"
  
posts:
  "sort" : ["date", "desc"]
  permalink: /:title/
  summary_lines: 10
  latest: 10
  paginator:
     layout: index2

pages:
  "sort" : ["date", "desc"]
  permalink: 'pretty'
  
widgets :
  analytics :
    use : google
    # -- config for google --
    tracking_id : 'UA-11790416-7'
    # -- config for getclicky  --
    # site_id : 9999999
  comments :
    use : disqus
    # -- config for disqus --
    short_name : damianhelme # Change This!
  google_prettify :
    # use : overloaded
    #linenums : true